spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/urlshortener
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
        show-sql: false